name: Daily Model Retraining

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC
  workflow_dispatch:     # Manual trigger

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model script
        run: python train_model.py

      - name: Commit and push updated model
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add best_model.pkl
          git commit -m "[Automated] Update best_model.pkl" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/AsmaCherifa/energy-consumption-prediction-mlflow.git HEAD:main
 