name: Daily Model testing

on:
  schedule:
    - cron: '0 0 * * *'  # At midnight UTC every day
  workflow_dispatch:     # Allow manual trigger as well

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model script
        run: python train_model.py