name: Energy Consumption Model Training

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:      # Allow manual triggers

permissions:
  contents: write

jobs:
  train-model:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://127.0.0.1:5000
      MODEL_VERSION: ${{ github.run_id }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow==2.8.1 scikit-learn pandas joblib

    - name: Create MLflow directory
      run: mkdir -p mlruns

    - name: Start MLflow server
      run: |
        mlflow server \
          --backend-store-uri sqlite:///mlruns/mlflow.db \
          --default-artifact-root ./mlruns \
          --host 0.0.0.0 &
        sleep 5

    - name: Run training
      run: |
        # Clean previous model
        if [ -f "best_model.pkl" ]; then
          rm -f best_model.pkl
          echo "Removed previous best_model.pkl"
        fi
        
        # Execute training
        python train_model.py
        
        # Verify model creation
        if [ ! -f "best_model.pkl" ]; then
          echo "ERROR: best_model.pkl not generated"
          exit 1
        fi

    - name: Push model to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add best_model.pkl
        git commit -m "[Automated] Update model ${{ github.run_id }}"
        git push

    - name: Send email notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "Energy Model Training - ${{ job.status }} (Run ${{ github.run_number }})"
        html_body: |
          <h2>Training Results</h2>
          <p><strong>Status</strong>: ${{ job.status }}</p>
          <p><strong>Run ID</strong>: ${{ github.run_id }}</p>
          <p><strong>Commit</strong>: ${{ github.sha }}</p>
          <p><a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Details</a></p>
        to: ${{ secrets.EMAIL_RECIPIENT }}  # Different from username
        from: "MLflow Bot <${{ secrets.EMAIL_USERNAME }}>"
        secure: true