name: Email Notification Test

on:
  workflow_dispatch:

jobs:
  test-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send test email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "TEST: Email Notification System"
          body: |
            This is a test email from GitHub Actions.
            
            If you received this, your email configuration works!
            
            Sent at: ${{ github.run_attempt }}
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.EMAIL_USERNAME }}